---
- name: Build and push Docker images
  hosts: all
  become: yes
  
  tasks:
   
  - name: Check if directory exists
    stat:
      path: /PFE-Front
    register: repo_stat

  - name: Clone repository
    shell: |
      git clone https://github.com/BenAmor1/PFE-Front.git /PFE-Front
    when: repo_stat.stat.exists == False

  - name: Pull repository
    shell: |
      cd /PFE-Front
      git pull 
    when: repo_stat.stat.exists == True
    
  - name: Build the Docker image
    shell: | 
      cd /PFE-Front
      docker build . -t reactfront/image
   
  - name: Tag the image
    shell: | 
      cd /PFE-Front
      docker tag reactfront/image beffa/project_pfe-2022:react_frontV1
  
  - name: Push the image to Docker Hub
    shell: docker push beffa/project_pfe-2022:react_frontV1
    
